FROM hashicorp/terraform:latest

ARG GCP_CREDENTIALS_PATH

# Copy gcp credentials file to container
COPY $GCP_CREDENTIALS_PATH /credentials/google/key.json
# COPY ./.credentials/google/key.json /credentials/google/key.json