taxi:
    target: prod
    outputs:
        dev:
            type: bigquery
            method: service-account
            project: "{{ env_var('GCP_PROJECT_ID') }}"
            dataset: "{{ env_var('GCS_BUCKET_DEV') }}"
            location: "{{ env_var('GCP_REGION') }}"
            threads: 2
            keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
        prod:
            type: bigquery
            method: service-account
            project: "{{ env_var('GCP_PROJECT_ID') }}"
            dataset: "{{ env_var('GCS_BUCKET_ANALYTICS') }}"
            location: "{{ env_var('GCP_REGION') }}"
            threads: 2
            keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
